name: FAC
version: 1.2.9-FIXED
main: de.febanhd.anticrash.plugin.AntiCrashPlugin
author: FebanHD
softdepend:
  - ProtocolLib

commands:
  unblockips:
  anticrash:
    aliases:
      - ac
      - fac
      - facanticrash